#!/usr/bin/env python3

import sys, os, subprocess, tempfile, argparse, codecs

parser = argparse.ArgumentParser(description='xattrvi - modify xattributes of files the simple way')

parser.add_argument('-v', action='count', default=0, dest='verbosity')
parser.add_argument('-e', '--encoding', action='store', dest='stdenc', type=str, default='utf-8', help='encoding to be used for value-decoding')
parser.add_argument('-s', '--edit-symlinks', action='store_false', dest='follow_symlink', default=True, help='edit xattributes of symlink itself instead of the targetfile')
parser.add_argument('filename', action='store', type=str, default=None, help='file that needs to get modified')

args = parser.parse_args(sys.argv[1:])

###
## let's get prepared, check if everything is in workingstate
###

# test if there is a file supplied at all
if not args.filename: sys.exit()

# test if that file actually exists
if not os.path.exists(args.filename):
	print("cannot find what you gave me", file=sys.stderr)
	sys.exit(1)

# test if a shitty encoding was supplied

try: codecs.lookup(args.stdenc)
except LookupError:
	print("I don't know that encoding", file=sys.stderr)
	sys.exit(2)
else:
	stdenc = args.stdenc

def newline_escape(string):   return string.replace('\n', '\\n')
def newline_unescape(string): return string.replace('\\n', '\n')


###
## now parse xattrvi-config, if there is one
###

ignored_keys = []
key_encodings = dict()

if os.path.isfile(os.path.expanduser('~/.config/xattrvirc')):
	with open(os.path.expanduser('~/.config/xattrvirc')) as f:
		for line in f:
			# omit comments and empty lines
			if line.startswith('#') or line.strip() == "": continue

			if line.startswith('ignore:'):
				ignored_keys.append(line.split(':', 1).strip())

			if line.startwith('key_encoding:'):
				_, key, enc = key_encodings.split(':', 2)
				try: codecs.lookup(enc)
				except LookupError:
					print("I don't know the encoding {0} in your xattrvirc, adding that key to the ignored ones".format(enc), file=sys.stderr)
					ignored_keys.append(key)
				else:
					key_encodings[key] = enc


# read out existing xattrs
xattrs = os.listxattr(args.filename)

def get_decoded_attr(filename, attr):
	if attr in key_encodings:
		return os.getxattr(filename, attr, follow_symlinks=args.follow_symlink).decode(key_encoding[attr])
	else:
		return os.getxattr(filename, attr, follow_symlinks=args.follow_symlink).decode(stdenc)


userxattrs = [
		( attr.split('.', 1)[1], get_decoded_attr(args.filename, attr) )
		for attr in xattrs
		if attr.startswith('user.') and not attr in ignored_keys
		]

otherxattrs = [
		( attr, get_decoded_attr(args.filename, attr) )
		for attr in xattrs
		if not attr.startswith('user.') and not attr in ignored_keys
		]

tmpfile = tempfile.NamedTemporaryFile()


# present current attributes
with open(tmpfile.name, 'w') as f:

	f.write("# attributes in namespace 'user':\n\n")
	f.write("\n".join([ "{0:10}   : {1}".format(key, newline_escape(value)) for key, value in userxattrs]))

	if len(otherxattrs) > 0:
		f.write("\n"*3)
		f.write("# attributes in other namespaces:\n\n")
		f.write("\n#".join([ "{0:10}   : {1}".format(key, value) for key, value in otherxattrs]))


# let the user change those attributes
retval = subprocess.call([os.environ['EDITOR'] or 'nano', tmpfile.name])
if retval != 0:
	print("!! Your editor {0} exited nonzero with {1}, removing stale tmpfile and aborting".format(os.environ['EDITOR'], retval), file=sys.stderr)
	sys.exit(1)


# parse and apply the user's changes
with open(tmpfile.name, 'r') as f:
	try:
		# perform simple syntax-check beforehand to print more helpful errors, just in case
		malformedLines = [line.strip() for line in f if line.strip() != "" and not line.startswith('#') and not ':' in line]
		if len(malformedLines) > 0:
			print("!! aborting, malformed lines in file:", file=sys.stderr)
			for line in malformedLines:
				print(">> " + line, file=sys.stderr)
				sys.exit(3)

		f.seek(0)

		# now parse the file
		newuserxattrlist = [line.strip().split(':', 1) for line in f if line.strip() != "" and not line.startswith('#')]
		newuserxattrs = [( key.strip(), newline_unescape(value.strip()) ) for key, value in newuserxattrlist]

	except UnicodeDecodeError:
		print("Errors parsing the file, aborting. Did you screw up the syntax?", file=sys.stderr)
		sys.exit(2)

	# now update the changed attributes
	changed = [] #remember changed properties for deletion procedure
	for key, value in set(newuserxattrs).difference(set(userxattrs)):
		print(":: updating {0}".format(key))
		try:
			changed.append(key)
			os.setxattr(args.filename, 'user.' + key, newline_unescape(value).encode(stdenc))
		except UnicodeEncodeError:
			print("!! error encoding {0} : {1}".format(key, value))

	# now delete all properties that are left over
	for key, _ in set(userxattrs).difference(set(newuserxattrs)): # set of all changed and removed attributes
		if key not in changed: # then the attribute vanished or key changed
			print(":: removing {0}".format(key))
			os.removexattr(args.filename, 'user.' + key)

