#!/usr/bin/env python3

import xattr, sys, os, subprocess
fsenc = sys.getfilesystemencoding()

# let's get prepared, check if everything is in workingstate
if len(sys.argv) < 0: sys.exit()

target = sys.argv[1]

if not os.path.exists(target):
	print("cannot find what you gave me", file=sys.stderr)
	sys.exit(1)



# read out existing xattrs
xattrs = os.listxattr(target)

userxattrs = [
		( attr.split('.', 1)[1], os.getxattr(target, attr).decode(fsenc) )
		for attr in xattrs
		if attr.startswith('user.')
		]

otherxattrs = [
		( attr, os.getxattr(target, xattr).decode(fsenc) )
		for attr in xattrs
		if not attr.startswith('user.')
		]



